import type { Metadata } from "next";
import "./globals.css";
import Head from 'next/head';1
import { NavBar } from "@/components/navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <NavBar />
        {children} 
        </body>
    </html>
  );
}
